### ISSUE TITLE
[TASK] Add the ability to pass custom arguments to the plugin from a json file

### ISSUE THREAD

**Issue by noorbuchi** [noorbuchi/GridGopher#21]
## Task Description and Info (what needs to be done?)

The user might want to pass custom arguments from to their written plugin. There is no current support for this in GridGopher, however, adding this feature is simple and straightforward.

## Steps and Acceptance Criteria (when is it considered complete?)

- [ ] 1. A CLI argument can accept the path to a json file that contains a variety of values that will be passed as arguments
- [ ] 2. `main.py` should accept that optional argument, open and read the json file
- [ ] 3. pass the content of the json file if an argument was passed to the plugins' run function
- [ ] 4. a `**kwagrs` should be included in the run function of the plugin

## Time to complete (approximately, how much time will this take?)

Add estimate here

## Person/People involved (who is working on this?)

@

## Other information

Anything else that doesn't fit in previous categories
