### ISSUE TITLE
[TASK] Complete README Information

### ISSUE THREAD

**Issue by noorbuchi** [noorbuchi/GridGopher#4]
## Task Description and Info (what needs to be done?)

Currently the README.md file doesn't contain any relevant information about the project. It's important for an open source project to have good documentation so other people can understand how to use it and contribute to it.

## Acceptance Criteria (when is it considered complete?)

- [ ] Documentation in README.md file describe the current progress made on the project and the plan moving forward
- [ ] Documentation is free of grammar and spelling errors
- [ ] The documentation passes Markdown linter

## Time to complete (approximately, how much time will this take?)

Add estimate here

## Person/People involved (who is working on this?)

@

## Other information

Markdown linter is not currently part of the project dependencies and it might be needed to run it locally or add it to the project workflow.
