### ISSUE TITLE
[TASK] Complete Sheet Collector

### ISSUE THREAD

**Issue by noorbuchi** [noorbuchi/GridGopher#5]
## Task Description and Info (what needs to be done?)

The current progress made on the Sheet Collector module has very limited functionality to demonstrate the ability to make calls to the Google Sheets API. More work is needed to collect and organize the data and to allow the user more control over this process. It's important to try and automate as much as possible of this part of the project.

## Acceptance Criteria (when is it considered complete?)

- [x] [Google sheets data can be collected, organized into a pandas data frame and stored.](https://github.com/noorbuchi/GatorGopher/projects/1#card-70690531)
- [x] [The user has control over the cell range of the data, and data columns to store.](https://github.com/noorbuchi/GatorGopher/projects/1#card-70690851)
- [x]  [The data will be organized by student email and stored as JSON files](https://github.com/noorbuchi/GatorGopher/projects/1#card-70691350)
- [x] The added code is well tested and adheres to common standards.
- [ ] There are no remaining `TODO`s in the code

## Time to complete (approximately, how much time will this take?)

Add estimate here

## Person/People involved (who is working on this?)

Preferably more than one person
@antlet 
@Yanqiao4396 
@tuduun 

## Other information

The tool `PluginBase` can be used in this situation to allow the user to create their own plugins for this part of the tool. This is not a priority for now.
